import { test } from 'node:test';
import assert from 'node:assert/strict';
import { normalize, summarize, fetchFeed, fresh } from '../data.js';
const now = Date.parse('2026-09-10T13:15:00Z');
const quakes = () => ({type:'FeatureCollection',metadata:{generated:now,status:200,count:0},features:[]});
const fx = () => ({base:'USD',amount:1,date:'2026-09-09',rates:{KRW:1336.2}});
const ok = data => ({status:'ok',data});
const error = {status:'error'};

test('empty, valid quake feed displays no magnitude, never M 0.0',()=>{const d=normalize('quakes',quakes(),now);assert.equal(d.count,0);assert.equal(d.magnitude,null);assert.equal(d.eventTime,null)});
test('missing quake features or inconsistent metadata is not an empty feed',()=>{for(const v of [{},{metadata:{generated:now}},{...quakes(),metadata:{generated:now,status:200,count:3}}])assert.throws(()=>normalize('quakes',v,now))});
test('quake event values and feed freshness are checked',()=>{const q=quakes();q.metadata.generated-=31*60000;assert.throws(()=>normalize('quakes',q,now));const b=quakes();b.metadata.count=1;b.features=[{properties:{mag:null,time:now,place:'Test'}}];assert.throws(()=>normalize('quakes',b,now))});
test('largest quake keeps full place name and its event time',()=>{const q=quakes();q.features=[{properties:{mag:4.8,time:now-1000,place:'A'}},{properties:{mag:5.3,time:now-2000,place:'126 km WSW of Alianza Cristiana, Peru'}}];q.metadata.count=2;const d=normalize('quakes',q,now);assert.equal(d.magnitude,5.3);assert.equal(d.eventTime,now-2000);assert.match(d.place,/Peru$/)});
test('FX requires USD base, one-unit amount, positive numeric KRW, and a valid recent date',()=>{assert.equal(normalize('fx',fx(),now).rate,1336.2);for(const override of [{base:'EUR'},{amount:100},{rates:{KRW:null}},{rates:{KRW:0}},{date:'2026-02-30'},{date:'2026-09-11'},{date:'2026-08-01'}])assert.throws(()=>normalize('fx',{...fx(),...override},now))});
test('weekend reference rate can remain valid without being treated as realtime',()=>{const v=fx();v.date='2026-09-04';assert.equal(normalize('fx',v,now).day,'2026-09-04')});
test('all feeds failing produces unknown, never safety',()=>{const s=summarize({weather:error,quakes:error,fx:error});assert.equal(s.tone,'unknown');assert.equal(s.word,'확인 필요');assert.match(s.title,/다시 확인/)});
test('partial failure remains unknown; known weather warning remains visible',()=>{assert.equal(summarize({weather:ok({reasons:[],temperature:22,complete:false}),quakes:ok({}),fx:error}).tone,'unknown');assert.equal(summarize({weather:ok({reasons:['강수확률 80% 이상']}),quakes:error,fx:error}).tone,'warn')});
test('complete weather summary displays temperature without claiming safety',()=>{const s=summarize({weather:ok({reasons:[],temperature:22,complete:true}),quakes:ok({}),fx:ok({})});assert.equal(s.word,'기준 미만');assert.match(s.title,/아산시 기온 22.0/);assert.equal(s.title.includes('안전'),false)});
test('loading cannot report normal',()=>assert.equal(summarize({weather:{status:'loading'},quakes:error,fx:error}).tone,'unknown'));
test('FX fallback also validates responses and never converts failures to numbers',async()=>{let calls=0;const result=await fetchFeed('fx',{now:()=>now,fetcher:async()=>({ok:true,json:async()=>++calls===1?{}:fx()})});assert.equal(calls,2);assert.equal(result.rate,1336.2);await assert.rejects(fetchFeed('fx',{now:()=>now,fetcher:async()=>({ok:false})}))});
test('JSON parse failure is isolated to its feed',async()=>{await assert.rejects(fetchFeed('weather',{now:()=>now,fetcher:async()=>({ok:true,json:async()=>{throw new SyntaxError('JSON')}})}));assert.equal((await fetchFeed('fx',{now:()=>now,fetcher:async()=>({ok:true,json:async()=>fx()})})).rate,1336.2)});
test('hung requests are aborted within the timeout',async()=>{let aborted=false;await assert.rejects(fetchFeed('weather',{timeout:10,fetcher:async(_,options)=>new Promise((_,reject)=>options.signal.addEventListener('abort',()=>{aborted=true;reject(new Error('aborted'))}))}));assert.equal(aborted,true)});
