const manuals=[
{id:'disaster',icon:'⌁',name:'재난·정전',summary:'침수·정전·통신 장애에 대비한 2~3일 생존 준비',source:'국민재난안전포털',url:'https://safekorea.go.kr/',now:['재난문자와 기상청 특보를 확인하세요.','휴대전화·보조배터리를 충전하세요.','가족 연락 방법과 만날 장소를 정하세요.'],prepare:['식수·간편식·생필품을 2~3일분 준비하세요.','손전등·라디오·여분 건전지를 한곳에 두세요.','반려동물 사료·복용약·이동장을 함께 챙기세요.'],avoid:['침수된 지하차도나 하천 진입','출처가 없는 대피 명령 공유','정전 중 엘리베이터 이용']},
{id:'finance',icon:'₩',name:'금융·결제 장애',summary:'결제망 장애에 대비하되 뱅크런을 유발하지 않는 준비',source:'금융위원회',url:'https://www.fsc.go.kr/',now:['은행과 카드사의 공식 공지만 확인하세요.','생활비 3~7일분 정도의 소액 현금만 준비하세요.','서로 다른 결제수단을 2개 이상 확보하세요.'],prepare:['자동이체·대출 납입일을 기록하세요.','예금자보호 대상을 공식 사이트에서 확인하세요.','중요 금융 연락처를 종이에도 적어두세요.'],avoid:['예금 전액을 한꺼번에 인출','소문만 보고 자산을 전부 환전','빚을 내어 금·달러·코인 매수']},
{id:'health',icon:'＋',name:'감염병·보건',summary:'기본 위생과 처방약을 준비하고 의료기관 안내를 따릅니다.',source:'질병관리청',url:'https://www.kdca.go.kr/',now:['마스크·체온계·손 세정제를 확인하세요.','복용약의 처방전과 잔여량을 확인하세요.','질병관리청과 보건소 공식 안내를 확인하세요.'],prepare:['가족별 복용약과 알레르기를 기록하세요.','상비약 용법과 유효기간을 확인하세요.','호흡기 증상이 있으면 환기하고 마스크를 착용하세요.'],avoid:['항생제 임의 구매·복용·나눠 먹기','남은 처방약을 다른 증상에 사용','검증되지 않은 치료법 공유']},
{id:'conflict',icon:'△',name:'전쟁·분쟁',summary:'정부 경보와 외교부 여행경보를 기준으로 판단합니다.',source:'외교부 해외안전여행',url:'https://www.0404.go.kr/',now:['정부 재난문자와 공식 브리핑을 확인하세요.','가족 비상 연락망과 대피 장소를 확인하세요.','신분증 등 중요문서 사본을 준비하세요.'],prepare:['라디오·손전등·보조배터리를 준비하세요.','차량 연료를 평소 절반 이상 유지하세요.','한 사람이 들 수 있는 생존배낭을 준비하세요.'],avoid:['군사시설 위치·사진 공유','확인되지 않은 동원·대피 소문 확산','상황을 보러 위험지역으로 이동']}
];
const $=s=>document.querySelector(s),fmt=v=>new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Seoul'}).format(new Date(v));
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#manualGrid').innerHTML=manuals.map(m=>`<button data-manual="${m.id}"><i>${m.icon}</i><div><b>${m.name}</b><span>${m.summary}</span><small>${m.source} ↗</small></div></button>`).join('');
function openManual(id){const m=manuals.find(x=>x.id===id),saved=JSON.parse(localStorage.getItem('canary-saved')||'[]');$('#dialogBody').innerHTML=`<p>${m.icon} VERIFIED ACTION GUIDE</p><h2>${m.name}</h2><p>${m.summary}</p><a href="${m.url}" target="_blank">근거: ${m.source} ↗</a><div class="steps"><section><h3>1 지금 확인</h3><ol>${m.now.map(x=>`<li>${x}</li>`).join('')}</ol></section><section><h3>2 미리 준비</h3><ol>${m.prepare.map(x=>`<li>${x}</li>`).join('')}</ol></section><section class="dont"><h3>! 하지 마세요</h3><ul>${m.avoid.map(x=>`<li>${x}</li>`).join('')}</ul></section></div><button class="save">${saved.includes(id)?'✓ 내 준비목록에 저장됨':'내 준비목록에 저장'}</button>`;$('.save').onclick=()=>{let a=JSON.parse(localStorage.getItem('canary-saved')||'[]');a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem('canary-saved',JSON.stringify(a));openManual(id)};$('#dialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-manual]');if(b)openManual(b.dataset.manual)});$('.close').onclick=()=>$('#dialog').close();
async function getJSON(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw Error(r.status);return await r.json()}finally{clearTimeout(t)}}
async function load(){const urls=['https://api.open-meteo.com/v1/forecast?latitude=36.7898&longitude=127.0018&current=temperature_2m&hourly=precipitation_probability,wind_speed_10m&daily=temperature_2m_max&wind_speed_unit=ms&timezone=Asia%2FSeoul&forecast_days=1','https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.geojson','https://api.frankfurter.app/latest?from=USD&to=KRW'];const [w,q,e]=await Promise.allSettled(urls.map(getJSON)),cards=$('#cards').children;let warn=false,errors=[];
if(w.status==='fulfilled'){const v=w.value,rain=Math.max(...v.hourly.precipitation_probability),wind=Math.max(...v.hourly.wind_speed_10m),max=v.daily.temperature_2m_max[0];warn=rain>=80||wind>=20||max>=35;cards[0].innerHTML=`<h3>☀ 아산 기상 <em>Open‑Meteo</em></h3><strong>${v.current.temperature_2m.toFixed(1)}°</strong><p>오늘 최고 ${max.toFixed(1)}℃</p><dl><div><dt>강수확률</dt><dd>${rain}%</dd></div><div><dt>최대 풍속</dt><dd>${wind.toFixed(1)} m/s</dd></div></dl>`}else{cards[0].innerHTML+='<p>자료 확인 실패</p>';errors.push('아산 기상')}
if(q.status==='fulfilled'){const f=q.value.features||[],top=[...f].sort((a,b)=>(b.properties.mag||0)-(a.properties.mag||0))[0];cards[1].innerHTML=`<h3>⌁ 세계 지진 <em>USGS 공식</em></h3><strong>${f.length}<small>건</small></strong><p>최근 24시간 규모 4.5 이상</p><dl><div><dt>최대 규모</dt><dd>M ${(top?.properties.mag||0).toFixed(1)}</dd></div><div><dt>발생지</dt><dd>${(top?.properties.place||'발생 없음').slice(0,18)}</dd></div></dl>`}else{cards[1].innerHTML+='<p>자료 확인 실패</p>';errors.push('USGS 지진')}
if(e.status==='fulfilled'){cards[2].innerHTML=`<h3>₩ 기준 환율 <em>Frankfurter</em></h3><strong>${e.value.rates.KRW.toLocaleString('ko-KR',{maximumFractionDigits:1})}<small>원</small></strong><p>미화 1달러 기준 참고환율</p><dl><div><dt>기준일</dt><dd>${e.value.date}</dd></div><div><dt>판단</dt><dd>단독 위험판단 안 함</dd></div></dl>`}else{cards[2].innerHTML+='<p>자료 확인 실패</p>';errors.push('참고 환율')}
document.body.classList.toggle('warn',warn);$('#stateWord').textContent=warn?'주의':'안전';$('#stateTitle').textContent=warn?'주의 신호 확인':'즉시 행동 신호 없음';$('#stateBody').textContent=warn?'아산 기상 예보에서 주의 기준을 넘는 값이 확인됐습니다.':'연결된 자료에서 현재 즉시 행동 기준을 넘은 신호는 없습니다.';$('#updated').textContent=`자료 확인 ${fmt(new Date())} · ${errors.length?'일부 자료 연결 지연':'공식 자료 확인 완료'}`}
$('#refresh').onclick=load;load();
function toast(s){const t=$('#toast');t.textContent=s;t.hidden=false;setTimeout(()=>t.hidden=true,5000)}
$('#notify').onclick=async()=>{if(!('Notification'in window))return toast('현재 브라우저는 알림을 지원하지 않습니다.');if(Notification.permission==='denied')return toast('사이트 설정에서 알림 권한을 허용해 주세요.');const p=await Notification.requestPermission();if(p!=='granted')return toast('알림 권한이 허용되지 않았습니다.');const reg=await navigator.serviceWorker.ready;await reg.showNotification('카나리아 알림 준비 완료',{body:'위험 신호를 확인할 준비가 됐습니다.',icon:'./icon-192.png'});$('#notify').textContent='알림 켜짐';toast('시험 알림을 보냈습니다.')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
