// YouTube 검색 결과를 oEmbed로 확인한 100개 영상.
window.CAT_TV_VIDEOS=[
  {
    "id": "7-BwZu0O_bk",
    "original": "8 Hrs Uninterrupted Birdbath Video for Cats to Watch😻8 Hours of Birds 🐦Splashing CatTV",
    "channel": "LensMyth",
    "title": "새 관찰 냥TV 01",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 100,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "fO3lUnuL5T4",
    "original": "12 Hr Uninterrupted Cat TV😻Birds Compilation Birdbath, Branches & Cherry Blossoms🐦No Ads @LensMyth",
    "channel": "LensMyth",
    "title": "새 관찰 냥TV 02",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 99,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "b_xKQ20jnQA",
    "original": "Cat TV 8 hours🐱Birds, chipmunks, squirrels, and the fall maple leaves(4K HDR)",
    "channel": "Birder King",
    "title": "새 관찰 냥TV 03",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 98,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "cEL4oNfySw8",
    "original": "⭐ The Best Cat TV - Cute Squirrels & Birds for Cats to Watch - Relaxing Nature Sounds in HD #cattv",
    "channel": "Cat Bird TV",
    "title": "새 관찰 냥TV 04",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 97,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "rURgdaQgXSs",
    "original": "Meow Meow TV 🐦 Cat TV for Cats to Watch | Colorful Birds & Squirrels in 4K HDR",
    "channel": "Meow Meow TV",
    "title": "새 관찰 냥TV 05",
    "category": "birds",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 96,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "zl-JtSlcKxw",
    "original": "Meow Meow TV 🐦 Cat TV for Cats to Watch | Colorful Birds & Squirrels in 4K HDR",
    "channel": "Meow Meow TV",
    "title": "새 관찰 냥TV 06",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 95,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "dOOADDIEUOc",
    "original": "This Cat Loves Birds so Much, He Turned an Old Mop Into a Bird Feeder 🌼🐦",
    "channel": "Neuro Nirvana",
    "title": "새 관찰 냥TV 07",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 94,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "-icCx_XGELk",
    "original": "The Best Cat TV ⭐ - Birds for Cats to Watch - Cat Games HD - Videos for Pets to Watch",
    "channel": "Cat Bird TV",
    "title": "새 관찰 냥TV 08",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 93,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "xbs7FT7dXYc",
    "original": "Videos for Cats to Watch - 8 Hour Birds Bonanza - Cat TV Bird Watch",
    "channel": "Paul Dinning",
    "title": "새 관찰 냥TV 09",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 92,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "KinjsVJn0-o",
    "original": "TV for Cats 😻8 Hours of Birds 🐦 and Squirrels 🐿Feeder Uninterrupted CatTV @LensMyth",
    "channel": "LensMyth",
    "title": "새 관찰 냥TV 10",
    "category": "birds",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 91,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "fAQOSsbJW2Q",
    "original": "Cat TV - A Video for Cats to Watch Garden Birds - 8 HOURS",
    "channel": "Paul Dinning",
    "title": "새 관찰 냥TV 11",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 90,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "3t1m7-xc6Pg",
    "original": "These Birds Made The Cat Watch For Hours 👀🐦 #CatTV #BirdTV #Wildlife",
    "channel": "Paws Garden TV",
    "title": "새 관찰 냥TV 12",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 89,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "yfOZ92kPYFQ",
    "original": "My Cat's Favorite TV Show! | CATFLIX | Cat TV for Cats to Watch | Squirrels, Relax Your Pets |",
    "channel": "emeL hit the Road ",
    "title": "새 관찰 냥TV 13",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 88,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "fKq_7r_Za8E",
    "original": "Meow Meow TV 🐦 Cat TV for Cats to Watch | Colorful Birds & Squirrels in 4K HDR",
    "channel": "Meow Meow TV",
    "title": "새 관찰 냥TV 14",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 87,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "-UPaggDAhfo",
    "original": "Sparrow Wild Pigeons Eating Seeds | Peaceful Nature Birds for Cats",
    "channel": "Nature Birds for cat ",
    "title": "새 관찰 냥TV 15",
    "category": "birds",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 86,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "cICTGlCkpD0",
    "original": "Bird Videos for Cats to Watch 🐱- 🐾 CAT TV, Backyard Birds HD 🌿- Cat Games 🐦 #asmr #relax #nature",
    "channel": "Cat Bird TV",
    "title": "새 관찰 냥TV 16",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 85,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "KePhGZIb-3o",
    "original": "Cat Watches A Cardinal Return To The Garden 🐱🐦 #CatTV #BirdsForCats #Nature",
    "channel": "PurrNest TV",
    "title": "새 관찰 냥TV 17",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 84,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "QSVxmzAqaIc",
    "original": "Meow Meow TV 🐦 Cat TV for Cats to Watch | Colorful Birds & Squirrels in 4K HDR",
    "channel": "Meow Meow TV",
    "title": "새 관찰 냥TV 18",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 83,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "ul_toQqw8AY",
    "original": "Cats Go Crazy For This Realistic Electronic Bird Toy #cat #pet #home",
    "channel": "Decorate the house",
    "title": "새 관찰 냥TV 19",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 82,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "Zp0wHss2QU8",
    "original": "Best Cat TV for Feline Entertainment | Sounds Cats React To",
    "channel": "Sounds Cats React To",
    "title": "새 관찰 냥TV 20",
    "category": "birds",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 81,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "onpRcvst9fg",
    "original": "4K Blue-and-white Flycatcher 💙 | Cozy Birds & Rain P40",
    "channel": "Quiet Lofi Garden",
    "title": "새 관찰 냥TV 21",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 80,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "afHIv66L3G8",
    "original": "cat videos for cats to watch no ads",
    "channel": "Cat TV Natural",
    "title": "새 관찰 냥TV 22",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 79,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "8SxAOqvfGSw",
    "original": "Cat TV 🐾 Mice Hide and Seek",
    "channel": "Studio Cat King",
    "title": "새 관찰 냥TV 23",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 78,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "MrSYP-cotdg",
    "original": "Cat TV for Cats to Watch 😺 Unlimited Birds Chipmunks Squirrels 🐿 8 Hours 4K HDR 60FPS",
    "channel": "Birder King",
    "title": "새 관찰 냥TV 24",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 77,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "02ML4zlcRpk",
    "original": "Cat TV for Cats to Watch 😺 Cute Birds, Chipmunks, Squirrels in the Forest 🐦🐿️ 8 Hours(4K HDR)",
    "channel": "Birder King",
    "title": "새 관찰 냥TV 25",
    "category": "birds",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 76,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "_kormY5Vgq8",
    "original": "Cat TV Extravaganza ~ Birds and Squirrels Everywhere ⭐ 8 HOURS ⭐",
    "channel": "Paul Dinning",
    "title": "새 관찰 냥TV 26",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 75,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "DqMYru_RWPs",
    "original": "Cat TV for Cats to Watch 😺 Endless Squirrels and Birds 🐿 8 Hours 4K HDR 60FPS",
    "channel": "Birder King",
    "title": "새 관찰 냥TV 27",
    "category": "birds",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 74,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "ZDK16sJEMHA",
    "original": "Videos for Cats ~ Cat TV Garden Birds Delight ⭐ 8 HOURS ⭐",
    "channel": "Paul Dinning",
    "title": "새 관찰 냥TV 28",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 73,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "mO4j4nWOf3M",
    "original": "TV for Cats 😻8 Hours of Uninterrupted Birds 🐦 and Squirrels NoAds  CatTV",
    "channel": "LensMyth",
    "title": "새 관찰 냥TV 29",
    "category": "birds",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 72,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "Dix58mO0Pbc",
    "original": "Cat TV for Cats to Watch 😺 Summer birds and ducks by the lake 🐦 Cute squirrels 🐿 8 Hours(4K HDR)",
    "channel": "Birder King",
    "title": "새 관찰 냥TV 30",
    "category": "birds",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 71,
    "why": "날갯짓과 작은 방향 전환이 냥이의 시선을 자연스럽게 끌어요."
  },
  {
    "id": "63QyMlUzMA0",
    "original": "MEOW! Video for Cats to Watch, Squirrels,Rabbits,Pigeons,Chipmunks,",
    "channel": "Yum Club",
    "title": "다람쥐·토끼 냥TV 01",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 100,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "wZPbsiJ4Cj8",
    "original": "Cat TV 4K HDR: Chipmunks, Birds, Squirrels, the Ugly Bunny - 8 Hours",
    "channel": "Birder King",
    "title": "다람쥐·토끼 냥TV 02",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 99,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "62IfaP2t3nU",
    "original": "10 Hour CAT TV - Wild Rabbits, Chipmunks, Squirrels and Birds - Aug 14, 2023",
    "channel": "Handsome Nature",
    "title": "다람쥐·토끼 냥TV 03",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 98,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "QjFqt1RXuzw",
    "original": "CatTV for cats to watch chipmunks. Videos for cats. #cattv #squirrel #chipmunks",
    "channel": "NatureArtPeace",
    "title": "다람쥐·토끼 냥TV 04",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 97,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "ED1DpnFoyjg",
    "original": "Cat TV for Cats to Watch Relaxing Videos of Birds, Chipmunks, and Squirrels 🐾  Entertain Your Cat",
    "channel": "Zen Cat TV",
    "title": "다람쥐·토끼 냥TV 05",
    "category": "squirrels",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 96,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "c0PHrSKlHSk",
    "original": "4K 6 hours cat TV. Rabbits chipmunks squirrels birds for cats to watch. #cattv #catrelaxation",
    "channel": "Zen Cat TV",
    "title": "다람쥐·토끼 냥TV 06",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 95,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "zTFG4aKvQg0",
    "original": "Chipmunks Cats TV 🐹 🐰",
    "channel": "Urban Hobbies",
    "title": "다람쥐·토끼 냥TV 07",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 94,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "Ee7vVI5R7PM",
    "original": "Cat TV for cats to watch 🐱🐶 Cute Chipmunks and Birds on Vacation 🐿 Dog TV 📺 8 Hours(4K HDR)",
    "channel": "Birder King",
    "title": "다람쥐·토끼 냥TV 08",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 93,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "lAeVxsa13Q4",
    "original": "Cat TV for Cats to Watch 😺 Little Red Squirrel Chipmunks and Birds 🐿 8 Hours 4K HDR 60FPS",
    "channel": "Birder King",
    "title": "다람쥐·토끼 냥TV 09",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 92,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "5hd9RQxnkzs",
    "original": "New Channel! Videos for Cats to Watch Squirrels, Chipmunks, and Birds. #videosforcats #squirrels",
    "channel": "Videos For Cats",
    "title": "다람쥐·토끼 냥TV 10",
    "category": "squirrels",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 91,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "5GejP21kcCY",
    "original": "Videos for Dogs and Cats - Chipmunks and Squirrels for 12 hours",
    "channel": "Calm Relaxing Noises",
    "title": "다람쥐·토끼 냥TV 11",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 90,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "B89cAWrMl5A",
    "original": "Cat TV for Cats - Best Wildlife Entertainment with Birds and Squirrels for Your Furry Friend!",
    "channel": "Chirping Paws",
    "title": "다람쥐·토끼 냥TV 12",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 89,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "XUsejMnR8SU",
    "original": "Cat TV to Watch: Hours of Birdwatching and Squirrel Action for Curious Cats",
    "channel": "Feline Forest TV",
    "title": "다람쥐·토끼 냥TV 13",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 88,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "2vtqHU714js",
    "original": "Bring Your Cat tv with Cute Chipmunk",
    "channel": "Backyard Nature",
    "title": "다람쥐·토끼 냥TV 14",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 87,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "O4zTl-E0XCQ",
    "original": "Cat TV for Cats 🐦🐿️ Birds & Squirrels for Endless Entertainment #CatTV  #CatTVforCats #VideoforCats",
    "channel": "Birdy for Cats",
    "title": "다람쥐·토끼 냥TV 15",
    "category": "squirrels",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 86,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "Bt_CpllKlL0",
    "original": "Cat TV - Chipmunk for Cats to Watch",
    "channel": "Bird Bliss",
    "title": "다람쥐·토끼 냥TV 16",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 85,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "sJAAVLCw_aI",
    "original": "Videos for Cats to Watch! Lots of Squirrels and Birds! 🐿️❤️ #videosforcats #squirrels #cattv",
    "channel": "Videos For Cats",
    "title": "다람쥐·토끼 냥TV 17",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 84,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "LvqmIrdPwT4",
    "original": "Videos for Dogs and Cats - Chipmunks and Squirrels for 12 hours",
    "channel": "Calm Relaxing Noises",
    "title": "다람쥐·토끼 냥TV 18",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 83,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "XhzyzLqYrg0",
    "original": "Cat TV for Cats 🐾 | Relaxing & Funny Cat Videos to Watch All Day | Entertainment for Your Kitten",
    "channel": "Heart Scene",
    "title": "다람쥐·토끼 냥TV 19",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 82,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "llYnuhoaMjw",
    "original": "Cat games on YouTube. Cat TV squirrels for cats to watch. #squirrelwatching #chipmunk #naturevideos",
    "channel": "Zen Cat TV",
    "title": "다람쥐·토끼 냥TV 20",
    "category": "squirrels",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 81,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "VPSouR6Zra8",
    "original": "Cat TV for Cats to Watch 😺 Fish, Birds, or Squirrels | Lo-Fi Music & Sound #CatTV #lofi",
    "channel": "CatSphere999",
    "title": "다람쥐·토끼 냥TV 21",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 80,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "S9vjGPzwT2o",
    "original": "CAT TV Nature Calm RELAX YOUR CAT",
    "channel": "Fun for cats tv",
    "title": "다람쥐·토끼 냥TV 22",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 79,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "LCjv7Vj0HKQ",
    "original": "Mouse Sneak Attack😺 Your Cat Won’t See This Coming! | Cat TV#MouseVideo #VideosForCats #CatsWatching",
    "channel": "WhiskerRun Studio",
    "title": "다람쥐·토끼 냥TV 23",
    "category": "squirrels",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 78,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "0IhIQiE_kFA",
    "original": "125 Cats Were Put in Front of a TV. They Watched 6% of the Time. #catfacts #cat #facts",
    "channel": "Professor Purr",
    "title": "다람쥐·토끼 냥TV 24",
    "category": "squirrels",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 77,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "vFVkwVJzsrI",
    "original": "Cat TV for Cats to Watch 😺🐰 Cute Birds, Rabbits, and Squirrels 🐦 8 Hours(4K HDR)",
    "channel": "Birder King",
    "title": "다람쥐·토끼 냥TV 25",
    "category": "squirrels",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 76,
    "why": "빠르게 달리고 멈추는 작은 동물의 움직임을 따라보기 좋아요."
  },
  {
    "id": "Mr292PG5vs8",
    "original": "CAT GAMES - 🐟 CATCHING FISH 1 HOUR VERSION (VIDEOS FOR CATS TO WATCH)",
    "channel": "CAT GAMES",
    "title": "물고기 사냥 냥TV 01",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 100,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "KxNm8313grs",
    "original": "Soothing Fish Tank For Cats | Aquarium Water Sounds | Focus, Sleep & Meditation | 6 Hours",
    "channel": "Relax Tank",
    "title": "물고기 사냥 냥TV 02",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 99,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "Cqt8YPbBUWM",
    "original": "Cat Games: Goldfish Aquarium! (Videos for Cats to Watch)",
    "channel": "Cat Lab Studios",
    "title": "물고기 사냥 냥TV 03",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 98,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "2Qel1R6Fgeo",
    "original": "Colorful Fish for Cats to Watch  🐟🐱 | Cat TV | Fun Moving Fish #catgames #catentertainment #cattoys",
    "channel": "Cat Toys Studio",
    "title": "물고기 사냥 냥TV 04",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 97,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "XycrYM5z9Kk",
    "original": "CAT TV | catch the fish, video for cats to watch 😺🐠 #cattv #happycat #videoforcats",
    "channel": "Zoë’s Cat TV",
    "title": "물고기 사냥 냥TV 05",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 96,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "6qxZtm32kFY",
    "original": "Vibrant Fish For Cats to Watch & Catch 🐠 Cat Game on screen",
    "channel": "Yoshi's Catflix",
    "title": "물고기 사냥 냥TV 06",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 95,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "rxn3EOnwmRg",
    "original": "Baby and Kitty Watch Fish in the Aquarium!",
    "channel": "1B TV ",
    "title": "물고기 사냥 냥TV 07",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 94,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "e_OQ-D7udLc",
    "original": "CORAL REEF AQUARIUM COLLECTION • 12 HOURS • BEST RELAX MUSIC • SLEEP MUSIC",
    "channel": "Cat Trumpet",
    "title": "물고기 사냥 냥TV 08",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 93,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "83UdhFEzDOg",
    "original": "Fish for cats to watch. Relaxing aquarium and water sounds. #aquariumfun #fishaquarium #cattv",
    "channel": "Zen Cat TV",
    "title": "물고기 사냥 냥TV 09",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 92,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "ATeit6LRXrc",
    "original": "4K Aquarium: Real Fish Swimming for Cats | Sounds Cats React To",
    "channel": "Sounds Cats React To",
    "title": "물고기 사냥 냥TV 10",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 91,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "q8ze3gncBVE",
    "original": "Colorful Aquarium Fish GAME for Cats to Watch 4K` #cattv #catentertainment #catworld",
    "channel": "catslover",
    "title": "물고기 사냥 냥TV 11",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 90,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "XNy5-8R-wRs",
    "original": "Goldfish Swimming for Cats Watch 🐠 #CatTV #music #fishtank #fish #aquascape #aquariumfish #aquarium",
    "channel": "ClawAndOrderTV",
    "title": "물고기 사냥 냥TV 12",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 89,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "fSQnarcnJBc",
    "original": "Shocking! The Kitten Can't Even Look at the Fish",
    "channel": "Mellow Pet House",
    "title": "물고기 사냥 냥TV 13",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 88,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "yrvCMl65ol4",
    "original": "BRAINROT FOR CATS LOOP",
    "channel": "Grace Baldwin",
    "title": "물고기 사냥 냥TV 14",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 87,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "ZPQpxV9muNc",
    "original": "Cat Thinks He’s Inside Fish Tank 😂",
    "channel": "NPC Pets",
    "title": "물고기 사냥 냥TV 15",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 86,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "kEFxjzN-k3E",
    "original": "CAT GAMES - 🐟 CATCHING FISH Game for Cats to Watch CAT TV with Birds, Mice & More #cattv #catgames",
    "channel": "Mews Views TV",
    "title": "물고기 사냥 냥TV 16",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 85,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "VZ2cqrV9uB0",
    "original": "Nika ate all my fish🥲 #cat #cats",
    "channel": "Princess Nika cat",
    "title": "물고기 사냥 냥TV 17",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 84,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "sJQqJ7cNkpQ",
    "original": "GIANT OSCAR FISH SWIMMING|Relaxing Video for Cats to Watch #animalswithcameras #cats #fyp #catwatch",
    "channel": "catslover",
    "title": "물고기 사냥 냥TV 18",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 83,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "dgF3nDCuwR8",
    "original": "Relaxing Aquarium Fish Tank 4K UHD 🌊 Peaceful Underwater World for Sleep",
    "channel": "Peaceful Aquarium ",
    "title": "물고기 사냥 냥TV 19",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 82,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "eYqgRvFxS7E",
    "original": "CAT GAMES - Cockroach + Fly +Ants For Cats to Watch 🪳🪰🐜 #cat #catgames #cats#viral #meow #cockroach",
    "channel": "Little Kittens Official",
    "title": "물고기 사냥 냥TV 20",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 81,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "dlS_gw1Uul0",
    "original": "Cat TV video Cats 🐾 | Relaxing & Funny Cat Videos to Watch All Day | Entertainment for Your Kitten",
    "channel": "Heart Scene",
    "title": "물고기 사냥 냥TV 21",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 80,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "WiehjqnjHEg",
    "original": "This Cat Lives Inside the Aquarium",
    "channel": "HJ Wizards",
    "title": "물고기 사냥 냥TV 22",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 79,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "zVeEJIt5l9o",
    "original": "Fish videos for cats to watch || cat and fish funny videos | #cute #cat #fishing",
    "channel": "Cat lover 07",
    "title": "물고기 사냥 냥TV 23",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 78,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "3gESf4K71u4",
    "original": "Fish on screen game for Cats",
    "channel": "Cat Games & TV - Bored Cat Channel",
    "title": "물고기 사냥 냥TV 24",
    "category": "fish",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 77,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "VlDcG_rAL_A",
    "original": "Video for cats 11Hours★고양이가 좋아하는 영상 11시간★물고기/열대어/하프음악/빗소리/힐링영상/고양이예능(Fish/Harp/Relaxing)(외출용ver.)",
    "channel": "체셔냥tv / forcatTV",
    "title": "물고기 사냥 냥TV 25",
    "category": "fish",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 76,
    "why": "물속을 부드럽게 오가는 움직임으로 편안한 사냥 놀이를 즐겨요."
  },
  {
    "id": "Os4LfEDOZG4",
    "original": "Cat Games - 🦋 Peacock Butterfly (Videos for cats to watch)",
    "channel": "CAT GAMES",
    "title": "작은 동물 자연 냥TV 01",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 100,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "xup3YCi1HfM",
    "original": "Cat Games | Ultimate Cat TV Bugs and Butterflies Compilation Vol 2 | Videos for Cats to Watch🐱",
    "channel": "CAT TV",
    "title": "작은 동물 자연 냥TV 02",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 99,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "7PKPCSns7BY",
    "original": "CAT GAMES - Mice, Butterflies, Ants, Strings. Videos for Cats to Watch | CAT & DOG TV | 1 Hour.",
    "channel": "TV BINI",
    "title": "작은 동물 자연 냥TV 03",
    "category": "nature",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 98,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "nM196tTz8Gc",
    "original": "Cat Games | Bugs & Butterflies for Cats to Watch – Birds, Mice & Lizards 🐱🦋🐦",
    "channel": "Ultimate Cat Games Tv",
    "title": "작은 동물 자연 냥TV 04",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 97,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "PvqJDavMYmA",
    "original": "Cat Games – Bugs TV Video for Cats to Watch 🐞🪳🪰 #cat #catgames #cattv #bugstvforcats #catbugstv",
    "channel": "Pet TV 4K | Cat TV & Guinea Pig ",
    "title": "작은 동물 자연 냥TV 05",
    "category": "nature",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 96,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "vzVUAIVMJeY",
    "original": "Cat Games: Shiny Bottle Flies! (Bugs for Cats)",
    "channel": "Cat Lab Studios",
    "title": "작은 동물 자연 냥TV 06",
    "category": "nature",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 95,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "LXncdrIxIUw",
    "original": "CAT Games | Ultimate Cat TV Bugs and Butterflies Compilation Vol 3 🪲 🐞🦋🦗🐜 | Videos For Cats to Watch",
    "channel": "CAT TV",
    "title": "작은 동물 자연 냥TV 07",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 94,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "3YfDMKICgrE",
    "original": "CAT Games | Ultimate Cat TV Bugs and Butterflies Compilation Vol 17 🪲 🐞🦋🦗🐜  Videos For Cats to Watch",
    "channel": "CAT TV",
    "title": "작은 동물 자연 냥TV 08",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 93,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "-iCiDyOjYiA",
    "original": "CAT Games | Ultimate Cat TV Bugs and Butterflies Compilation Vol 16 🪲 🐞🦋🦗🐜  Videos For Cats to Watch",
    "channel": "CAT TV",
    "title": "작은 동물 자연 냥TV 09",
    "category": "nature",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 92,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "mWsoWYgENwg",
    "original": "[Cat TV]  🦋 🐱 butterflies for cats to watch",
    "channel": "Game for cats 猫用動画 貓電視",
    "title": "작은 동물 자연 냥TV 10",
    "category": "nature",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 91,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "NOfT3SXSpos",
    "original": "Cat Game: Flying Fly on Screen",
    "channel": "Games-Cat",
    "title": "작은 동물 자연 냥TV 11",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 90,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "QQo1U2wgsDs",
    "original": "ULTIMATE Cat TV 🐀 REAL Mouse Hole GAME for Cats | Feline Enrichment",
    "channel": "Next to Nature",
    "title": "작은 동물 자연 냥TV 12",
    "category": "nature",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 89,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "mz6hY0CFp0A",
    "original": "Cat Games | Cockroach for cat to watch - Ultimate Cat TV Bugs |  Entertainment Video for Cat",
    "channel": "CAT GAMES VIDEO",
    "title": "작은 동물 자연 냥TV 13",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 88,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "6abyOXoX8b8",
    "original": "Cat TV | Catch the Butterfly",
    "channel": "Cat TV Hub",
    "title": "작은 동물 자연 냥TV 14",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 87,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "xn3whXbZvYk",
    "original": "CAT TV | CAT GAME TV #cats #spider #cattv #butterfly #ants #mouse #bird #insects #catgames #bug",
    "channel": "Cat's Game",
    "title": "작은 동물 자연 냥TV 15",
    "category": "nature",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 86,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "TvuM_FrEn74",
    "original": "Cockroach for cats to watch 🪳 #cat #catgames #cats#viral #meow #cockroach",
    "channel": "Cat Tele",
    "title": "작은 동물 자연 냥TV 16",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 85,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "vowHZqMZt5I",
    "original": "Cat Games | Mouse Video For Cat To Watch | Cat TV  For Cats #cat #catandmousegame#cattv #catgames",
    "channel": "Little Kittens Official",
    "title": "작은 동물 자연 냥TV 17",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 84,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "qZRdCgzbHO0",
    "original": "Mouse for cats to watch 🐭📺😻",
    "channel": "CATS TV - Game for Cats",
    "title": "작은 동물 자연 냥TV 18",
    "category": "nature",
    "stimulus": "high",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 83,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "WFSb4TgxIDc",
    "original": "Cat Games: Cockroach Invasion! (Fast Bugs for Cats)",
    "channel": "Cat Lab Studios",
    "title": "작은 동물 자연 냥TV 19",
    "category": "nature",
    "stimulus": "medium",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 82,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  },
  {
    "id": "UONwzVg0Uos",
    "original": "CAT GAMES - Cockroach Game for Cats🐈 #cattv #videosforcats #gameforcats #catgames #￼cockroachforcat",
    "channel": "Mews Views TV",
    "title": "작은 동물 자연 냥TV 20",
    "category": "nature",
    "stimulus": "low",
    "duration": "장시간 영상",
    "minutes": 480,
    "score": 81,
    "why": "작은 생물과 자연의 불규칙한 움직임을 차분하게 관찰할 수 있어요."
  }
];
