import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = path => readFileSync(resolve(root, path), 'utf8');
const write = (path, text) => writeFileSync(resolve(root, path), text);
const hash = text => createHash('sha256').update(text).digest('hex').slice(0, 12);
const combat = read('src/combat.js'), combatPath = `assets/combat-${hash(combat)}.js`;
const app = read('src/app.js').replace('"./combat.js"', `"./${combatPath.split('/').pop()}"`);
if (app === read('src/app.js')) throw new Error('Combat module import was not replaced');
const appPath = `assets/app-${hash(app)}.js`;
const css = read('src/upgrade.css'), cssPath = `assets/upgrade-${hash(css)}.css`;
write(combatPath, combat); write(appPath, app); write(cssPath, css);
const html = read('src/index.html').replace('./src/app.js', `./${appPath}`).replace('./src/upgrade.css', `./${cssPath}`);
write('index.html', html);
const core = ['./', './index.html', './manifest.webmanifest', './favicon.svg', './icons/icon-192.png', './icons/icon-512.png',
  `./${appPath}`, `./${combatPath}`, `./${cssPath}`, './assets/react-runtime.js', './assets/index-DkfX9k8Z.css'];
const version = hash(html + combat + css);
write('sw.js', `// Generated by scripts/build.mjs. Scope: this game only.
const CACHE = "odyssey-pages-v2-${version}";
const CORE = ${JSON.stringify(core)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(CORE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('odyssey-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  const scope = new URL(self.registration.scope);
  if (event.request.method !== 'GET' || url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname) || event.request.headers.has('range')) return;
  event.respondWith(fetch(event.request).then(response => {
    if (response.ok) {
      const copy = response.clone();
      event.waitUntil(caches.open(CACHE).then(cache => cache.put(event.request, copy)).catch(() => {}));
    }
    return response;
  }).catch(async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(event.request);
    return hit || (event.request.mode === 'navigate' ? await cache.match('./') : null) || Response.error();
  }));
});
`);
console.log(`Built Odyssey: ${appPath}, ${combatPath}, ${cssPath}`);
