// Shared place metadata keeps displayed terrain and scoring inputs identical.
export const SPOTS = [
  { id: "gujina", name: "꾸지나무골 해수욕장", region: "taean", source: "gujina", sourceLabel: "만대항", campZone: "north-taean", terrain: "암반·모래" },
  { id: "sinduri", name: "신두리 해수욕장", region: "taean", source: "sinduri", sourceLabel: "신두리항", campZone: "north-taean", terrain: "모래·갯벌" },
  { id: "hakampo", name: "학암포 해수욕장", region: "taean", source: "hakampo", sourceLabel: "학암포항", campZone: "north-taean", terrain: "암반·모래" },
  { id: "iwon_dike", name: "이원방조제", region: "taean", source: "iwon_dike", sourceLabel: "이원방조제", campZone: "north-taean", terrain: "방조제·펄·모래" },
  { id: "guryepo", name: "구례포 해수욕장", region: "taean", source: "guryepo", sourceLabel: "학암포항", campZone: "north-taean", terrain: "암반·모래·웅덩이" },
  { id: "gureumpo", name: "구름포 해수욕장", region: "taean", source: "gureumpo", sourceLabel: "모항항", campZone: "west-taean", terrain: "암반·모래·웅덩이" },
  { id: "uihang", name: "의항 해수욕장", region: "taean", source: "uihang", sourceLabel: "모항항", campZone: "west-taean", terrain: "암반·모래" },
  { id: "gareumi", name: "갈음이 해수욕장", region: "taean", source: "gareumi", sourceLabel: "안흥항", campZone: "west-taean", terrain: "암반·모래·웅덩이" },
  { id: "mallipo", name: "만리포·천리포", region: "taean", source: "mallipo", sourceLabel: "모항항", campZone: "west-taean", terrain: "모래·암반" },
  { id: "mongsanpo", name: "몽산포 해수욕장", region: "taean", source: "mongsanpo", sourceLabel: "몽산포항", campZone: "central-taean", terrain: "넓은 갯벌" },
  { id: "dangampo", name: "당암포구", region: "taean", source: "dangampo", sourceLabel: "당암포구", campZone: "central-taean", terrain: "포구·펄갯벌·수로" },
  { id: "jinsanri", name: "진산리 갯벌체험장", region: "taean", source: "jinsanri", sourceLabel: "진산리어촌계", campZone: "central-taean", terrain: "단단한 모래·갯벌" },
  { id: "kkotji", name: "꽃지·방포 해변", region: "taean", source: "kkotji", sourceLabel: "방포항", campZone: "anmyeon", terrain: "암반·모래" },
  { id: "gomsom", name: "곰섬해수욕장", region: "taean", source: "gomsom", sourceLabel: "마검포항", campZone: "central-taean", terrain: "갯벌·모래" },
  { id: "mageompo", name: "마검포항·마검포해수욕장", region: "taean", source: "mageompo", sourceLabel: "마검포항", campZone: "central-taean", terrain: "포구·갯벌·모래" },
  { id: "deuruni", name: "드르니항", region: "taean", source: "deuruni", sourceLabel: "드르니항", campZone: "anmyeon", terrain: "갯벌·수로" },
  { id: "sinjindo", name: "신진도항", region: "taean", source: "sinjindo", sourceLabel: "신진도항", campZone: "west-taean", terrain: "암반·방파제" },
  { id: "anheung", name: "안흥항", region: "taean", source: "anheung", sourceLabel: "안흥항", campZone: "west-taean", terrain: "암반·방파제" },
  { id: "yeonpo", name: "연포 해수욕장", region: "taean", source: "yeonpo", sourceLabel: "연포항", campZone: "central-taean", terrain: "모래·암반" },
  { id: "padory", name: "파도리 해수욕장", region: "taean", source: "padory", sourceLabel: "모항항", campZone: "west-taean", terrain: "자갈·암반" },
  { id: "eoeundol", name: "어은돌 해수욕장", region: "taean", source: "eoeundol", sourceLabel: "모항항", campZone: "west-taean", terrain: "모래·암반" },
  { id: "baekripo", name: "백리포 해수욕장", region: "taean", source: "baekripo", sourceLabel: "모항항", campZone: "west-taean", terrain: "모래·암반" },
  { id: "cheongpodae", name: "청포대 해수욕장", region: "taean", source: "cheongpodae", sourceLabel: "몽산포항", campZone: "central-taean", terrain: "넓은 갯벌" },
  { id: "dalsanpo", name: "달산포 해수욕장", region: "taean", source: "dalsanpo", sourceLabel: "몽산포항", campZone: "central-taean", terrain: "모래·갯벌" },
  { id: "sambong", name: "삼봉 해수욕장", region: "taean", source: "sambong", sourceLabel: "백사장항", campZone: "anmyeon", terrain: "모래·갯벌" },
  { id: "batgae", name: "밧개 해수욕장", region: "taean", source: "batgae", sourceLabel: "방포항", campZone: "anmyeon", terrain: "모래·갯벌" },
  { id: "saetbyeol", name: "샛별 해수욕장", region: "taean", source: "saetbyeol", sourceLabel: "방포항", campZone: "anmyeon", terrain: "모래·암반" },
  { id: "baramarae", name: "바람아래 해수욕장", region: "taean", source: "baramarae", sourceLabel: "영목항", campZone: "anmyeon", terrain: "갯벌·모래" },
  { id: "yeonyukgyo", name: "태안 연육교", region: "taean", source: "yeonyukgyo", sourceLabel: "안면대교", campZone: "anmyeon", terrain: "갯벌·수로" },
  { id: "hwangdo", name: "황도·황도항", region: "taean", source: "hwangdo", sourceLabel: "황도항", campZone: "anmyeon", terrain: "갯벌·바위" },
  { id: "ganwoldo", name: "간월도", region: "seosan", source: "ganwoldo", sourceLabel: "간월도항", campZone: "seosan", terrain: "갯벌·돌밭" },
  { id: "jungri", name: "중리어촌체험마을", region: "seosan", source: "jungri", sourceLabel: "중리항", campZone: "seosan", terrain: "갯벌" },
  { id: "garorim", name: "가로림만", region: "seosan", source: "garorim", sourceLabel: "구도항", campZone: "seosan", terrain: "갯벌·수로" },
  { id: "beolcheonpo", name: "벌천포해수욕장", region: "seosan", source: "beolcheonpo", sourceLabel: "벌천포", campZone: "seosan", terrain: "몽돌·갯벌·갯바위" },
  { id: "samgilpo", name: "삼길포항", region: "seosan", source: "samgilpo", sourceLabel: "삼길포항", campZone: "seosan", terrain: "항구·방파제·갯바위" },
  { id: "muchangpo", name: "무창포 해수욕장", region: "boryeong", source: "muchangpo", sourceLabel: "무창포항", campZone: "boryeong", terrain: "모래·갯벌" },
  { id: "doksan", name: "보령 독산 해수욕장", region: "boryeong", source: "doksan", sourceLabel: "무창포항", campZone: "boryeong", terrain: "넓은 모래·갯벌" },
  { id: "daecheon", name: "대천 해수욕장", region: "boryeong", source: "daecheon", sourceLabel: "대천항", campZone: "boryeong", terrain: "모래" },
  { id: "seondori", name: "선도리 갯벌체험장", region: "boryeong", source: "seondori", sourceLabel: "홍원항", campZone: "boryeong", terrain: "갯벌" },
  { id: "chunjangdae", name: "서천 춘장대 해수욕장", region: "boryeong", source: "chunjangdae", sourceLabel: "홍원항", campZone: "boryeong", terrain: "모래·갯벌" },
  { id: "biin", name: "비인해변", region: "boryeong", source: "biin", sourceLabel: "비인해변", campZone: "boryeong", terrain: "넓은 모래·갯벌" },
  { id: "waemok", name: "왜목마을", region: "dangjin", source: "waemok", sourceLabel: "왜목항", campZone: "dangjin", terrain: "돌밭·갯벌" },
  { id: "janggohang", name: "장고항", region: "dangjin", source: "janggohang", sourceLabel: "장고항", campZone: "dangjin", terrain: "포구·갯벌·갯바위" },
  { id: "seokmun_dike", name: "석문방조제", region: "dangjin", source: "seokmun_dike", sourceLabel: "석문방조제", campZone: "dangjin", terrain: "방조제·펄갯벌·깊은 수로" },
  { id: "dobido", name: "도비도", region: "dangjin", source: "dobido", sourceLabel: "도비도항", campZone: "dangjin", terrain: "갯벌·수로" },
  { id: "haengdamdo", name: "행담도", region: "dangjin", source: "haengdamdo", sourceLabel: "행담도", campZone: "dangjin", terrain: "섬·펄갯벌·수로" },
  { id: "jebudo", name: "제부도", region: "metro", source: "jebudo", sourceLabel: "제부항", campZone: "metro", terrain: "갯벌·암반" },
  { id: "daebudo", name: "대부도", region: "metro", source: "daebudo", sourceLabel: "방아머리항", campZone: "metro", terrain: "갯벌" },
  { id: "dongmak", name: "강화 동막해변", region: "metro", source: "dongmak", sourceLabel: "분오리항", campZone: "metro", terrain: "갯벌" },
  { id: "deokjeokdo", name: "덕적도", region: "metro", source: "deokjeokdo", sourceLabel: "덕적도항", campZone: "metro", terrain: "모래·갯벌" },
  { id: "janggyeongri", name: "장경리 해수욕장", region: "metro", source: "janggyeongri", sourceLabel: "영흥도항", campZone: "metro", terrain: "모래·갯벌" },
  { id: "seonjaedo", name: "선재도 측도", region: "metro", source: "seonjaedo", sourceLabel: "선재도항", campZone: "metro", terrain: "갯벌·수로" },
  { id: "eulwangri", name: "을왕리 해수욕장", region: "metro", source: "eulwangri", sourceLabel: "용유항", campZone: "metro", terrain: "모래·암반" },
  { id: "keunmuri", name: "큰무리어촌체험마을", region: "metro", source: "keunmuri", sourceLabel: "큰무리항", campZone: "metro", terrain: "갯벌" },
  { id: "ganghwa_bunori", name: "강화 분오리돈대 갯벌", region: "metro", source: "ganghwa_bunori", sourceLabel: "분오리항", campZone: "metro", terrain: "갯벌" },
  { id: "ganghwa_janghwari", name: "강화 장화리 갯벌", region: "metro", source: "ganghwa_janghwari", sourceLabel: "장화리", campZone: "metro", terrain: "갯벌" },
  { id: "ganghwa_hwangsando", name: "강화 황산도 갯벌", region: "metro", source: "ganghwa_hwangsando", sourceLabel: "황산도항", campZone: "metro", terrain: "갯벌" },
  { id: "ganghwa_oepoh", name: "강화 외포항 갯벌", region: "metro", source: "ganghwa_oepoh", sourceLabel: "외포항", campZone: "metro", terrain: "갯벌·수로" },
  { id: "muui_silmi", name: "무의도 실미 해수욕장", region: "metro", source: "muui_silmi", sourceLabel: "실미도", campZone: "metro", terrain: "모래·갯벌" },
  { id: "somuui", name: "소무의도 갯벌", region: "metro", source: "somuui", sourceLabel: "소무의항", campZone: "metro", terrain: "갯벌·암반" },
  { id: "songdo", name: "송도 갯벌", region: "metro", source: "songdo", sourceLabel: "인천항", campZone: "metro", terrain: "갯벌" },
  { id: "seonjaedo_eochon", name: "선재도 어촌체험마을", region: "metro", source: "seonjaedo_eochon", sourceLabel: "선재도항", campZone: "metro", terrain: "갯벌" },
  { id: "masian", name: "마시안 해변", region: "metro", source: "masian", sourceLabel: "용유항", campZone: "metro", terrain: "모래·갯벌" },
  { id: "seonnyeobawi", name: "선녀바위 해수욕장", region: "metro", source: "seonnyeobawi", sourceLabel: "용유항", campZone: "metro", terrain: "모래·암반" },
  { id: "muui_hanagae", name: "무의도 하나개 해수욕장", region: "metro", source: "muui_hanagae", sourceLabel: "하나개항", campZone: "metro", terrain: "모래·갯벌" },
  { id: "wangsan", name: "왕산 해수욕장", region: "metro", source: "wangsan", sourceLabel: "용유항", campZone: "metro", terrain: "모래·갯벌" },
  { id: "seokmodo", name: "석모도 민머루 해수욕장", region: "metro", source: "seokmodo", sourceLabel: "석모도", campZone: "metro", terrain: "모래·갯벌" },
  { id: "bangameori", name: "대부도 방아머리 해수욕장", region: "metro", source: "bangameori", sourceLabel: "방아머리항", campZone: "metro", terrain: "모래·갯벌" },
  { id: "daebudo_dongju", name: "대부도 동주염전 갯벌", region: "metro", source: "daebudo_dongju", sourceLabel: "대부도", campZone: "metro", terrain: "갯벌" },
  { id: "daebudo_yeongjeon", name: "대부도 영전 갯벌", region: "metro", source: "daebudo_yeongjeon", sourceLabel: "대부도", campZone: "metro", terrain: "갯벌" },
  { id: "ippado", name: "입파도", region: "metro", source: "ippado", sourceLabel: "입파도", campZone: "metro", terrain: "암반·모래" },
  { id: "jonghyeon", name: "종현어촌체험마을", region: "metro", source: "jonghyeon", sourceLabel: "대부도", campZone: "metro", terrain: "갯벌" },
  { id: "daemyeong", name: "김포 대명항", region: "metro", source: "daemyeong", sourceLabel: "대명항", campZone: "metro", terrain: "갯벌·수로" },
  { id: "heulgot", name: "흘곶어촌체험마을", region: "metro", source: "heulgot", sourceLabel: "대부도", campZone: "metro", terrain: "갯벌" },
  { id: "jeburi_eochon", name: "제부리어촌체험마을", region: "metro", source: "jeburi_eochon", sourceLabel: "제부항", campZone: "metro", terrain: "갯벌" },
  { id: "gungpyeongri", name: "궁평리어촌체험마을", region: "metro", source: "gungpyeongri", sourceLabel: "궁평항", campZone: "metro", terrain: "갯벌" },
  { id: "seongam", name: "대부도 선감어촌체험마을", region: "metro", source: "seongam", sourceLabel: "선감항", campZone: "metro", terrain: "갯벌" },
  { id: "baekmiri", name: "백미리 해수욕장", region: "metro", source: "baekmiri", sourceLabel: "백미리", campZone: "metro", terrain: "갯벌·모래" },
  { id: "ueumdo", name: "우음도", region: "metro", source: "ueumdo", sourceLabel: "시화호", campZone: "metro", terrain: "갯벌" },
  { id: "pungdo", name: "풍도어촌체험마을", region: "metro", source: "pungdo", sourceLabel: "풍도항", campZone: "metro", terrain: "암반·갯벌" },
  { id: "oido", name: "오이도어촌체험마을", region: "metro", source: "oido", sourceLabel: "오이도", campZone: "metro", terrain: "갯벌" },
  { id: "byeonsan", name: "변산해수욕장", region: "honam", source: "byeonsan", sourceLabel: "변산해수욕장", campZone: "honam", terrain: "고운 모래·완만한 갯벌" },
  { id: "seonyudo", name: "군산 선유도", region: "honam", source: "seonyudo", sourceLabel: "선유도항", campZone: "honam", terrain: "모래·갯벌" },
  { id: "mokpo", name: "목포 갯벌", region: "honam", source: "mokpo", sourceLabel: "목포", campZone: "honam", terrain: "갯벌" },
  { id: "muan", name: "무안 도리포 갯벌", region: "honam", source: "muan", sourceLabel: "도리포항", campZone: "honam", terrain: "갯벌" },
];
