// Generated by scripts/build.mjs. Scope: this game only.
const CACHE = "odyssey-pages-v2-5bf631371469";
const CORE = ["./","./index.html","./manifest.webmanifest","./favicon.svg","./icons/icon-192.png","./icons/icon-512.png","./assets/app-1e7dec554de9.js","./assets/combat-73ac889f59bb.js","./assets/upgrade-d96ae16c0ab2.css","./assets/react-runtime.js","./assets/index-DkfX9k8Z.css"];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(CORE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('odyssey-') && key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  const scope = new URL(self.registration.scope);
  if (event.request.method !== 'GET' || url.origin !== scope.origin || !url.pathname.startsWith(scope.pathname) || event.request.headers.has('range')) return;
  event.respondWith(fetch(event.request).then(response => {
    if (response.ok) {
      const copy = response.clone();
      event.waitUntil(caches.open(CACHE).then(cache => cache.put(event.request, copy)).catch(() => {}));
    }
    return response;
  }).catch(async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(event.request);
    return hit || (event.request.mode === 'navigate' ? await cache.match('./') : null) || Response.error();
  }));
});
